module Main

open Feliz
open Browser.Dom
open Fable.Core.JsInterop

// We only need to load the SCSS styles
// when in debug because in "production" it will be
// generated by Nacara
#if DEBUG
importSideEffects "./../../docs/style.scss"
#endif

ReactDOM.render(
    Demo.Component,
    // Uncomment this line if you need to play with the Prototype component
    // Make sure to revert to using 'Demo.Component' before publishing
    // as this is the component used for the demo
    // Prototype.Component,
    document.getElementById "demo-container"
)
